In [1]:
a=10

In [2]:
b=20

In [13]:
if a>b:
    print("a is greater than b")
else:
        print("b is greater than a")
    
    
    
        
   

b is greater than a


In [14]:
a=10
b=20
c=30

In [15]:
if (a>b) & (a>c):
    print("a is greatest")
elif(b>a) & (b>c):
    print("b is greatest")
else:
    print("c is greatest")

c is greatest


In [16]:
#if with touple:

In [17]:
tup=('a','b','c')

In [18]:
type(tup)

tuple

In [19]:
if 'a' in tup:
    print(" a is present in tup") 

 a is present in tup


In [20]:
if 'z' in tup:
    print(" a is present in tup")
else:
    print("z is not present in tup")

z is not present in tup


In [21]:
#if with list:

In [22]:
l1=['p','q','r','s']

In [23]:
type(l1)

list

In [1]:
if l1[1]=='q':
    l1[1]='t'

NameError: name 'l1' is not defined

In [30]:
l1

['p', 't', 'r', 's']

In [31]:
#if with dictionary

In [32]:
d1={'k1':10, 'k2':20, 'k3':30}

In [33]:
type(d1)

dict

In [35]:
if d1['k3'] == 30:
    d1['k3'] =d1['k3']+100

In [36]:
d1

{'k1': 10, 'k2': 20, 'k3': 130}

In [37]:
#while loop:

In [2]:
i=1
while i<=10:
    print(i)
    i=i+2

1
3
5
7
9


In [44]:
i=1
n=2
while i<=10:
    print(n,"*",i,"=",n*i)
    i=i+1

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [45]:
#while with list

In [46]:
l1=[1,2,3,4,5]

In [47]:
i= 0

In [52]:
while i<len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [53]:
l1

[101, 102, 103, 104, 105]

In [54]:
l1={'mango','apple','grapes','orange'}

In [55]:
for i in l1:
    print(i)

orange
mango
apple
grapes


In [57]:
l2=['orange','black','white']
l3=['chair','book','laptop']
for i in l2:
    for j in l3:
        print(i,j)

orange chair
orange book
orange laptop
black chair
black book
black laptop
white chair
white book
white laptop


In [63]:
 
    def hello():
        print("hello world")

In [62]:
hello()

hello world


In [73]:
def add_10(x):
    return x+10 


In [74]:
add_10(9)

19

In [75]:
add_10(5)

15

In [85]:
def odd_even(x):
    if x%2==0:
        print(x, "is even")
    else:
        print(x, "is odd")

In [77]:
odd_even(10)

10 is even


In [86]:
odd_even(3)

3 is odd


In [87]:
g=lambda x:x*x*x

In [88]:
g(10)

1000

In [89]:
g(7)

343

In [90]:
#lambda with filter

In [91]:
l1=[1,2,3,4,5,6,7,8,9,10]

In [92]:
list(filter(lambda x: (x%2!=0),l1))

[1, 3, 5, 7, 9]

In [93]:
list(filter(lambda x: (x%2==0),l1))

[2, 4, 6, 8, 10]

In [94]:
#lambda with map

In [95]:
l1=[1,3,5,7,9]

In [96]:
list(map(lambda x:x*2,l1))

[2, 6, 10, 14, 18]

In [97]:
from functools import reduce

In [98]:
sum = reduce(lambda x,y:x+y,l1)

In [99]:
sum

25

In [100]:
#object oriented programming language

In [101]:
class phone:
    def make_call(self):
        print("making phone calls")
    def play_game(self):
        print("playing games")

In [102]:
p1=phone()

In [103]:
p1.make_call()

making phone calls


In [104]:
p1.play_game()

playing games


In [107]:
class phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("making phone calls")
    def play_game(self):
        print("playing games")
    

In [108]:
p2=phone()

In [110]:
p2.set_color('blue')

In [111]:
p2.show_color()

'blue'

In [112]:
p2.set_cost(10000)

In [113]:
p2.show_cost()

10000

In [114]:
p2.make_call()

making phone calls


In [115]:
p2.play_game()

playing games


In [116]:
#creating a class with constructor

In [117]:
class Employee:
    def __init__(self,name,age,salary,gender):
        self.name=name
        self.age=age
        self.salary=salary
        self.gender=gender
        
    def Employee_details(self):
        print("name of employee is",self.name)
        print("age of employee is",self.age)
        print("salary of employee is",self.salary)
        print("gender of employee is",self.gender)

In [121]:
E1=Employee('raj',18,10000,'male')

In [122]:
E1.Employee_details()

name of employee is raj
age of employee is 18
salary of employee is 10000
gender of employee is male


In [123]:
#INHERITENCE in python 

In [143]:
class vehicle:
    def __init__(self,mileage,cost):
        self.mileage=mileage
        self.cost=cost
    def show_vehicle_details(self):
        print("i am a vehicle")
        print("mileage of vehicle is",self.mileage)
        print("cost of vehicle is",self.cost) 

In [125]:
v1=vehicle(40,45000)

In [146]:
v1.show_details()

i am a vehicle
mileage of vehicle is 40
cost of vehicle is 45000


In [145]:
class car(vehicle):
    def show_car(self):
        print("i am a car") 

In [128]:
c1=car(200,1200)

In [129]:
c1.show_details()

i am a vehicle
mileage of vehicle is 200
cost of vehicle is 1200


In [130]:
c1.show_car()

i am a car


In [131]:
#over-riding init method

In [148]:
class car(vehicle):
    def __init__(self,mileage,cost,tyres,hp):
        super().__init__(mileage,cost)
        self.tyres=tyres
        self.hp=hp
    def show_car_details(self):
        print("i am a car")
        print("tyres of vehicle is",self.tyres)
        print("hp of vehicle is",self.hp)

In [149]:
c1=car(20,12000,4,300)

In [150]:
c1.show_car_details()

i am a car
tyres of vehicle is 4
hp of vehicle is 300


In [152]:
class vehicle:
    def __init__(self,mileage,cost):
        self.mileage=mileage
        self.cost=cost
    def show_vehicle_details(self):
        print("i am a vehicle")
        print("mileage of vehicle is",self.mileage)
        print("cost of vehicle is",self.cost) 

In [153]:
c1.show_vehicle_details()

i am a vehicle
mileage of vehicle is 20
cost of vehicle is 12000


In [154]:
#multiple inheritance in python 

In [155]:
class parent1():
    def assign_string_one(self,str1):
        self.str1=str1
    def show_string_one(self):
        return self.str1

In [156]:
class parent2():
    def assign_string_two(self,str2):
        self.str2=str2
    def show_string_two(self):
        return self.str2

In [157]:
class derived(parent1,parent2):
    def assign_string_three(self,str3):
        self.str3=str3
    def show_string_three(self):
        return self.str3 

In [158]:
d1=derived()

In [161]:
d1.assign_string_one("one")






In [171]:
class parent2():
    def assign_string_two(self,str2):
        self.str2=str2
    def show_string_two(self):
        return self.str2 


In [166]:
d1.assign_string_two("two")

AttributeError: 'derived' object has no attribute 'assign_string_two'

In [167]:
d1.assign_string_three("three")

In [168]:
d1.show_string_one()

'one'

In [169]:
d1.show_string_two()

AttributeError: 'derived' object has no attribute 'show_string_two'

In [170]:
d1.show_string_three()

'three'

In [172]:
#multi-level inheritance

In [184]:
class parent():
    def assign_name(self,name):
        self.name=name
    def show_name(self):
            return self.name

In [185]:
class child(parent):
    def assign_age(self,age):
        self.age=age
    def show_age(self):
            return self.age

In [186]:
class grandchild(child):
    def assign_gender(self,gender):
        self.gender=gender
    def show_gender(self):
            return self.gender 

In [187]:
gc = grandchild() 

In [188]:
gc.assign_name('raj')


In [189]:
gc.assign_age(18)

In [179]:
gc.assign_gender("male")


In [193]:
gc.show_name()

AttributeError: 'grandchild' object has no attribute 'show_name'

In [194]:
gc.show_age()

AttributeError: 'grandchild' object has no attribute 'show_age'

In [195]:
gc.show_gender()

AttributeError: 'grandchild' object has no attribute 'show_gender'

In [196]:
gc.show_name()

AttributeError: 'grandchild' object has no attribute 'show_name'

In [197]:
class parent():
    def assign_name(self,name):
        self.name=name
    def show_name(self):
            return self.name

In [198]:
class child(parent):
    def assign_age(self,age):
        self.age=age
    def show_age(self):
            return self.age

In [199]:
class grandchild(child):
    def assign_gender(self,gender):
        self.gender=gender
    def show_gender(self):
            return self.gender 

In [200]:
gc=grandchild()

In [201]:
gc.assign_name("raj")

In [202]:
gc.assign_age(18)

In [203]:
gc.assign_gender("male")

In [204]:
gc.show_name()

'raj'

In [205]:
gc.show_age()

18

In [206]:
gc.show_gender()

'male'

In [207]:
# libraries:numpy(numeric computation)

In [208]:
import numpy as np 
n1=np.array([10,20,30,40])

In [209]:
n1

array([10, 20, 30, 40])

In [215]:
import numpy as np 
n2=np.array([[10,20,30,40],[50,60,70,80]])

In [216]:
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [217]:
type(n1)

numpy.ndarray

In [218]:
type(n2)

numpy.ndarray

In [221]:
import numpy as np 
n1=np.zeros((1,2)) 


In [222]:
n1

array([[0., 0.]])

In [223]:
import numpy as np 
n1=np.zeros((5,5)) 
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [227]:
import numpy as np 
n1=np.full((2,2),10)

In [228]:
n1

array([[10, 10],
       [10, 10]])

In [231]:
import numpy as np 
n1=np.arange(10,20)


In [232]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [233]:
import numpy as np 
n1=np.arange(10,20,5)


In [234]:
n1

array([10, 15])

In [235]:
import numpy as np 
n1=np.random.randint(1,100,5)


In [236]:
n1

array([19, 23, 66, 31, 51])

In [237]:
import numpy as np 
n2=np.array([[10,20,30,40],[50,60,70,80]])


In [238]:
n2.shape

(2, 4)

In [240]:
n2.shape = (4,2)

In [241]:
n2.shape

(4, 2)

In [242]:
n2


array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [243]:
import numpy as np
n1 = np.array([10,20,30])
n2=np.array([40,50,60]) 

In [244]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [246]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [247]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [248]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70])
n2=np.array([40,50,60,70,80,90]) 

In [250]:
np.intersect1d(n1,n2)

array([40, 50, 60, 70])

In [252]:
np.setdiff1d(n2,n1)

array([80, 90])

In [254]:
import numpy as np 
n1= np.array([10,20])
n2=np.array([30,40])


In [255]:
np.sum([n1,n2])

100

In [256]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [257]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [258]:
n1=n1+1

In [259]:
n1

array([11, 21])

In [260]:
n1=n1-1

In [261]:
n1

array([10, 20])

In [262]:
n1=n1*2

In [263]:
n1

array([20, 40])

In [264]:
n1=n1/2

In [265]:
n1

array([10., 20.])

In [266]:
np.mean(n1)

15.0

In [267]:
np.median(n1)

15.0

In [268]:
np.std(n1)

5.0

In [269]:
import numpy as np 
n1=np.array([1,5,3,100,4,48])

In [270]:
np.std(n1)

36.59424666377065

In [271]:
np.save('my_numpy',n1)

In [273]:
n1=np.load('my_numpy.npy')

In [274]:
n1

array([  1,   5,   3, 100,   4,  48])

In [275]:
 #libary: pandas(data manipulation)

In [282]:
import pandas as pd
s1=pd.Series([1,2,3,4,5]) 




In [283]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [284]:
type(s1)

pandas.core.series.Series

In [285]:
import pandas as pd
s1=pd.Series([1,2,3,4,5], index=['a','b','c','d','e']) 


In [286]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [288]:
import pandas as pd
s1=pd.Series({'a':10,'b':20,'c':30})  

In [289]:
s1

a    10
b    20
c    30
dtype: int64

In [290]:
type(s1)

pandas.core.series.Series

In [293]:
import pandas as pd
s1=pd.Series({'a':10,'b':20,'c':30}, index=['b','c','a'])

In [294]:
s1

b    20
c    30
a    10
dtype: int64

In [295]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9])

In [296]:
s1[3]

4

In [297]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [298]:
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [299]:
s1 +5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [300]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9]) 
s2= pd.Series([10,11,12,13,14,15,16,17,18])

In [301]:
s1+s2

0    11
1    13
2    15
3    17
4    19
5    21
6    23
7    25
8    27
dtype: int64

In [302]:
s1-s2

0   -9
1   -9
2   -9
3   -9
4   -9
5   -9
6   -9
7   -9
8   -9
dtype: int64

In [303]:
s1*s2

0     10
1     22
2     36
3     52
4     70
5     90
6    112
7    136
8    162
dtype: int64

In [304]:
s1/s2

0    0.100000
1    0.181818
2    0.250000
3    0.307692
4    0.357143
5    0.400000
6    0.437500
7    0.470588
8    0.500000
dtype: float64

In [305]:
#pandas dataframes

In [307]:
import pandas as pd
pd.DataFrame({'name':['bob','sam','anni'],'marks':[76,77,78]}) 

name  marks
0   bob     76
1   sam     77
2  anni     78

In [2]:
iris = pd.read_csv

NameError: name 'pd' is not defined